### PR TITLE
Rename secrets.py to make gitignore work

### PR DESCRIPTION
**Pull request by IsaacG**

### CODE REVIEW

**Comment by DolceTriade** [comment]
I have been using 
```
 git update-index --assume-unchanged secrets.py
```

When I have changes to secrets.py (to add new constants or something), I run
```
 git update-index --no-assume-unchanged secrets.py
```

Maybe this approach is preferable?

**Comment by IsaacG** [comment]
That's good for you and maybe even me but there are other people and we should stop leaking it out repeatedly. This solution will make it far, far harder for a leak to occur.

**Review by DolceTriade — APPROVED** [review]

**Comment by DolceTriade** [comment]
Fair enough.

**Comment by IsaacG** [comment]
Redoing at https://github.com/Verdagon/ghvz/pull/55

**Pull request closed without merging**
